name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      # Set up cookbook.json from GitHub secret
      - name: Set Up Cookbook JSON
        run: echo "$COOKBOOK_JSON" > backend/cookbook.json
        env:
          COOKBOOK_JSON: ${{ secrets.COOKBOOK_JSON }}

      # Run tests
      - name: Run Tests
        run: python -m pytest backend/tests

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass

    steps:
      # Checkout the repository again
      - name: Checkout Code
        uses: actions/checkout@v3

      # Trigger deployment to Render
      - name: Trigger Deployment to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Using secrets for security
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "srv-cvnr95re5dus73dvhjj0",
              "branch": "master"
            }' \
            https://api.render.com/v1/services/srv-cvnr95re5dus73dvhjj0/deploys

